version: '3'
services:
    webapp:
        build:
            context: "."
            dockerfile: "Dockerfile"
        image: "flaskapp"
        ports:
            - "8080:80"
        depends_on:
            - redis-server
        restart: "on-failure"
    redis-server:
        image: "redis"
        restart: "on-failure"